### ISSUE TITLE
#79 is breaking travis on python-2.7

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#154]
After merging the #145 I noticed that travis is complaining on python-2.7,
as this build fine on other python (3.4, 3.5, 3.6) https://travis-ci.org/afewmail/afew/builds/259724537?utm_source=github_status&utm_medium=notification

```
======================================================================

ERROR: test_multi_line_config (afew.tests.test_multi_line_config.TestMultiLineConfig)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/afewmail/afew/afew/tests/test_multi_line_config.py", line 25, in setUp

    settings.clear ()

AttributeError: 'SafeConfigParser' object has no attribute 'clear'

----------------------------------------------------------------------

Ran 5 tests in 0.169s

FAILED (errors=1)

Test failed: <unittest.runner.TextTestResult run=5 errors=1 failures=0>

error: Test failed: <unittest.runner.TextTestResult run=5 errors=1 failures=0>

The command "coverage run --source=afew setup.py test" exited with 1.
```

**Comment by GuillaumeSeren** [comment]
According to https://docs.python.org/3/library/configparser.html,
the function .clear() was added in python-3.2, explaining the problem.

@flokli What do you think ?

**Comment by flokli** [comment]
`.clear()` usage was introduced in #79, not #154, for which no travis build was triggered, as travis wasn't used in 2014. I reverted this PR for now, which should fix the build on master again, and we can rework the patch in #79

**Comment by GuillaumeSeren** [comment]
@flokli ok fine to me !

**Comment by GuillaumeSeren** [comment]
Despite this tiny itch in the tests (only for 2.7 tho), we have fast-forward all pending/merge-able request,
and we should be able to concentrate more effort on current (than old) ones.

**Comment by flokli** [comment]
Python 2.7 was dropped from travis since quite some time, and we don't run on 2.7 anymore, so this can be closed.
